server:
  port: 80

spring:
  redis:
    host: redis
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  datasource:
    username: yoti
    password: Yoti!@#$
    url: jdbc:mysql://rm-rj9kz81i1kskvib9088250.mysql.rds.aliyuncs.com:3306/smart-home?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  application:
    name: smart-home-web-oauth2

management:
  endpoints:
    web:
      exposure:
        include: "*"

