version: "3"

services:

  nginx:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    build:
      context: ./nginx-docker
      dockerfile: Dockerfile
    image: sh-nginx
    container_name: sh-nginx
    ports:
      - "80:80"
      - "443:443"
    privileged: true #是否让docker 应用容器 获取宿主机root权限（特殊权限）
    restart: on-failure #失败重启
    networks:
      - mynet #加入"mynet"网络
    volumes:
      - /data/smart-home/nginx/html:/nginx/html
      - /data/smart-home/nginx/files:/nginx/files
      - /data/smart-home/nginx/logs:/var/log/nginx
      - /data/smart-home/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - redis
      - nacos
      - app-oauth2
      - app
      - web
      - voice-alexa-web
      - voice-google-web
      - godfs

  godfs:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fastdfs:1.0.0         #docker pull sjqzhang/go-fastdfs
    container_name: godfs
    privileged: true
    restart: always
    volumes:
      - /data/smart-home/godfs/data:/usr/local/go-fastdfs/data
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"

  redis:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    build:
      context: ./redis-docker
      dockerfile: Dockerfile
    image: sh-redis
    container_name: sh-redis
    privileged: true #是否让docker 应用容器 获取宿主机root权限（特殊权限）
    expose:
      - "6379"
    restart: always
    networks:
      - mynet
    volumes:
      - /data/smart-home/redis/data:/data
      - /data/smart-home/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf

  nacos:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    build:
      context: ./nacos-docker
      dockerfile: Dockerfile
    image: sh-nacos
    container_name: sh-nacos
    privileged: true
    ports:
      - "8848:8848"
    environment:
      - MODE=standalone
    restart: always
    networks:
      - mynet

  app-oauth2:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    build:
      context: ./app-oauth2
      dockerfile: Dockerfile
    image: sh-app-oauth2
    privileged: true
    container_name: sh-app-oauth2
    expose:
      - "80"
    restart: always
    networks:
      - mynet
    volumes:
      - /data/smart-home/app-oauth2/logs:/logs
    depends_on:
      - nacos
      - redis

  web-oauth2:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    build:
      context: ./web-oauth2
      dockerfile: Dockerfile
    image: sh-web-oauth2
    privileged: true
    container_name: sh-web-oauth2
    expose:
      - "80"
    restart: always
    networks:
      - mynet
    volumes:
      - /data/smart-home/web-oauth2/logs:/logs
    depends_on:
      - nacos
      - redis

  app:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    build:
      context: ./smart-home-app
      dockerfile: Dockerfile
    image: sh-app
    container_name: sh-app
    privileged: true
    expose:
      - "80"
    restart: always
    networks:
      - mynet
    volumes:
      - /data/smart-home/app/logs:/logs
    depends_on:
      - nacos
      - service
      - app-oauth2
      - redis

  web:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    build:
      context: ./smart-home-service
      dockerfile: Dockerfile
    image: sh-web
    container_name: sh-web
    privileged: true
    expose:
      - "80"
    restart: always
    networks:
      - mynet
    volumes:
      - /data/smart-home/web/logs:/logs
    depends_on:
      - service
      - nacos
      - web-oauth2
      - redis

  voice-google-web:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    build:
      context: ./smart-home-voice-google-web
      dockerfile: Dockerfile
    image: sh-voice-google-web
    container_name: sh-voice-google-web
    privileged: true
    expose:
      - "80"
    restart: always
    networks:
      - mynet
    volumes:
      - /data/smart-home/voice-google-web/logs:/logs
    depends_on:
      - service
      - nacos
      - app-oauth2
      - redis

  voice-alexa-web:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    build:
      context: ./smart-home-voice-alexa-web
      dockerfile: Dockerfile
    image: sh-voice-alexa-web
    container_name: sh-voice-alexa-web
    privileged: true
    expose:
      - "80"
    restart: always
    networks:
      - mynet
    volumes:
      - /data/smart-home/voice-alexa-web/logs:/logs
    depends_on:
      - service
      - nacos
      - app-oauth2
      - redis

  service:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    build:
      context: ./smart-home-service
      dockerfile: Dockerfile
    image: sh-service
    container_name: sh-service
    privileged: true
    expose:
      - "80"
    restart: always
    networks:
      - mynet
    volumes:
      - /data/smart-home/service/logs:/logs
    depends_on:
      - app-oauth2
      - nacos
      - xxl-job-admin
      - redis
      - godfs

  xxl-job-admin:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    build:
      context: ./xxl-job-admin
      dockerfile: Dockerfile
    image: sh-xxl-job-admin
    container_name: sh-xxl-job-admin
    privileged: true
    expose:
      - "80"
    restart: always
    networks:
      - mynet
    volumes:
      - /data/smart-home/xxl-job-admin/logs:/logs

networks:
  mynet:
    external: true

