server:
  port: 80

spring:
  application:
    name: smart-home-voice-alexa
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  oauth2:
    resourceId: alexa_client
    clientId: alexa_client
    clientSecret: secret
    checkTokenUrl: http://smart-home-app-oauth2/oauth/check_token
  jackson:
    default-property-inclusion: non_null
    generator:
      write_numbers_as_strings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
