server:
  port: 11035

spring:
  application:
    name: smart-home-voice-alexa
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.108:8848
  oauth2:
    resourceId: alexa_client
    clientId: alexa_client
    clientSecret: secret
    checkTokenUrl: http://app-oauth2/oauth/check_token
  jackson:
    default-property-inclusion: non_null
    generator:
      write_numbers_as_strings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

