spring:
  redis:
    host: 192.168.0.108
    port: 6379

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.108:3306/sos_api?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 3
      max-active: 10
      max-wait: 50000
      keep-alive-between-time-millis: 50000
      keep-alive: false

  jackson:
    default-property-inclusion: non_null

# 逻辑已删除
mybatis-plus:
  global-config:
    db-config:
      # 逻辑已删除
      logic-delete-value: 1
      # 逻辑未删除
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    combaomidou.mybatisplus.samples.quickstart: info