server:
  port: 11001

spring:
  application:
    name: smart-home-app
security:
  oauth2:
    client:
      client-id: c1
      client-secret: secret
      access-token-uri: http://127.0.0.1:11111/oauth/check_token
      user-authorization-uri: http://127.0.0.1:11111/oauth/authorize
      grant-type: password,refresh_token
    resource:
      token-info-uri: http://127.0.0.1:11111/oauth/check_token
