server:
  port: 11001

spring:
  application:
    name: smart-home-app
  oauth2:
    resource-id: rs1
    client-id: c1
    client-secret: secret
    check-token-url: http://localhost:33333/oauth/check_token