server:
  port: 11031

spring:
  application:
    name: smart-home-app
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.108:8848
  oauth2:
    resourceId: rs1
    clientId: c1
    clientSecret: secret
    checkTokenUrl: http://app-oauth2/oauth/check_token
  jackson:
    default-property-inclusion: non_null
    generator:
      write_numbers_as_strings: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

