server:
  port: 80
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4

spring:
  application:
    name: smart-home-voice-google
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

  oauth2:
    resourceId: google_client
    clientId: google_client
    clientSecret: secret
    checkTokenUrl: http://smart-home-app-oauth2/oauth/check_token

  jackson:
    default-property-inclusion: non_null
    generator:
      write_numbers_as_strings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    com:
      alibaba:
        nacos:
          client: warn
feign:
  hystrix:
    enabled: true
  httpclient:
    # 关闭 ApacheHttpClient
    enabled: false
  client:
    config:
      # 服务名，填写 default 为所有服务，或者指定某服务，例如：annoroad-beta
      default:
        # 连接超时，10秒
        connectTimeout: 10000
        # 读取超时，20秒
        readTimeout: 20000
  okhttp:
    # 开启 okhttp
    enabled: true
