server:
  port: 80

spring:
  application:
    name: smart-home-voice-google
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

  oauth2:
    resourceId: google_client
    clientId: google_client
    clientSecret: secret
    checkTokenUrl: http://app-oauth2/oauth/check_token

  jackson:
    default-property-inclusion: non_null
    generator:
      write_numbers_as_strings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    com:
      alibaba:
        nacos:
          client: warn
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false # 关闭 ApacheHttpClient
  client:
    config:
      default: # 服务名，填写 default 为所有服务，或者指定某服务，例如：annoroad-beta
        connectTimeout: 10000 # 连接超时，10秒
        readTimeout: 20000 # 读取超时，20秒
  okhttp:
    enabled: true # 开启 okhttp
