server:
  port: 80

spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  #    sentinel:
  #      transport:
  #        dashboard: sentinel:8858
  application:
    name: smart-home-service
  redis:
    database: 0
    host: redis
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
    password:
  datasource:
    username: yoti
    password: Yoti!@#$
    url: jdbc:mysql://rm-rj9kz81i1kskvib9088250.mysql.rds.aliyuncs.com:3306/smart-home?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 3
      max-active: 10
      max-wait: 50000
      keep-alive-between-time-millis: 50000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      keep-alive: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 阿里邮箱
ali:
  account:
    accessKey: LTAI4FwCUMja2wn74aYAtG2i
    secret: wYGK907NaHNvK7jDvocLC1v4m7H7vj

# mqtt 配置
mqtt:
  host: tcp://emqx:1883
  username: guest
  password: guest

mybatis-plus:
  configuration:
    # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 邀请返回地址
invite:
  host:
    accept: service:80/open/smart/home/accept/invite
    refuse: service:80/open/smart/home/refuse/invite
  # 发送邮件的有效时间
  effective:
    time: 7

# xxl-job
xxl:
  job:
    admin:
#      addresses: http://172.18.0.7:80/xxl-job-admin
      addresses: http://xxl-job-admin:80/xxl-job-admin
    accessToken: # token
    executor: # 执行器信息
      appname: ${spring.application.name}
      address:
      ip:
      port: 9999
      logpath: /smart-home/sh-service/logs/xxl-job
      logretentiondays: 30

#文件服务器路径
goFastDFS:
  file:
    path: http://file.ecoeler.com/
    group: group1
