server:
  port: 11011

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.108:8848
    sentinel:
      transport:
        dashboard: 192.168.0.108:8858
  application:
    name: smart-home-service
  redis:
    database: 0
    host: 192.168.0.108
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
    password:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.108:3306/smart-home?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 3
      max-active: 10
      max-wait: 50000
      keep-alive-between-time-millis: 50000
      keep-alive: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 阿里邮箱
ali:
  account:
    accessKey: LTAI4FwCUMja2wn74aYAtG2i
    secret: wYGK907NaHNvK7jDvocLC1v4m7H7vj

# mqtt 配置
mqtt:
  host: tcp://106.52.74.193:1883
  username: tang
  password: 321456