spring:
  application:
    name: smart-home-web
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

  oauth2:
    resource-id: rs1
    client-id: c1
    client-secret: secret
    check-token-url: http://web-oauth2/oauth/check_token
    token-url: http://web-oauth2/oauth/token

  jackson:
    default-property-inclusion: non_null
    generator:
      write_numbers_as_strings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 80


#ribbon的超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
